### PR TITLE
Remove inner declare

### PR DESCRIPTION
**Pull request by wolthers**
Fixes the template so that $params and $path are not using declare
image

### CODE REVIEW

**Comment by yesmeck** [comment]
Thanks, could please update snapshot by running `npm run test -- --run -u` under root dir.

**Comment by wolthers** [comment]
> Thanks, could please update snapshot by running `npm run test -- --run -u` under root dir.

Done. Also added react-dom to e2e since I couldn't run pnpm i without it.

**Comment by yesmeck** [comment]
Merged in https://github.com/yesmeck/remix-routes/commit/7cff5745fe291e1d83bcfcef352fd76f1089a053. However, adding `react-dom` to dependencies breaks [test](https://github.com/yesmeck/remix-routes/pull/56/files#diff-a5e3f4c08ea6c4d8328e70311049ff7aebf0dbe18e5907d09a0166650097b16aL30) which I need some time to investigate. Thank you.

**Comment by wolthers** [comment]
> Merged in [7cff574](https://github.com/yesmeck/remix-routes/commit/7cff5745fe291e1d83bcfcef352fd76f1089a053). However, adding `react-dom` to dependencies breaks [test](https://github.com/yesmeck/remix-routes/pull/56/files#diff-a5e3f4c08ea6c4d8328e70311049ff7aebf0dbe18e5907d09a0166650097b16aL30) which I need some time to investigate. Thank you.

Anything I can do to help move it along?

**Comment by yesmeck** [comment]
> > Merged in [7cff574](https://github.com/yesmeck/remix-routes/commit/7cff5745fe291e1d83bcfcef352fd76f1089a053). However, adding `react-dom` to dependencies breaks [test](https://github.com/yesmeck/remix-routes/pull/56/files#diff-a5e3f4c08ea6c4d8328e70311049ff7aebf0dbe18e5907d09a0166650097b16aL30) which I need some time to investigate. Thank you.
> 
> Anything I can do to help move it along?

I have no idea why changing dependencies breaks tests; you can look into it if you're interested.

**Comment by wolthers** [comment]
@yesmeck Most likely a minor version that has *some* breaking change. Me installing react dom generated a new lockfile, bumping all the packages to newest minor version. If you lock all the dependencies to patches it works:

image

**Comment by wolthers** [comment]
@yesmeck This is the offending release: https://github.com/remix-run/remix/blob/remix%401.14.1/packages/remix-dev/CHANGELOG.md#patch-changes-1. Does that ring a bell for you?

**Pull request closed without merging**
